
.PHONY : links
links:
	ln -sf libSDL2-2.0.so.0.0.0 libSDL2-2.0.so.0
	ln -sf libSDL2-2.0.so.0.0.0 libSDL2.so
	ln -sf libSDL2_ttf-2.0.so.0.10.2 libSDL2_ttf-2.0.so.0
	ln -sf libSDL2_ttf-2.0.so.0.10.2 libSDL2_ttf.so
